//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonutCP.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonutDataBase : DbContext
    {
        public DonutDataBase()
            : base("name=DonutDataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Files> Files { get; set; }
        public virtual DbSet<High_Lights> High_Lights { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<NoteAccess> NoteAccess { get; set; }
        public virtual DbSet<NoteMediaContent> NoteMediaContent { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
