//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonutCP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class High_Lights
    {
        public int Id { get; set; }
        public int Note_Id { get; set; }
        public int Start_Text_Index { get; set; }
        public int Length_Hight_Light { get; set; }
        public string Text_Hight_Light { get; set; }
        public int Author_Id { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual Users Users { get; set; }
    }
}
