//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonutCP.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class NoteMediaContent
    {
        public int Id { get; set; }
        public int NoteId { get; set; }
        public int FileId { get; set; }
    
        public virtual Files Files { get; set; }
        public virtual Note Note { get; set; }
    }
}
